version: '3.8'

services:
  # Vector database for semantic search
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # API
      - "6334:6334"  # Web UI
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  qdrant_data:
    driver: local 